#include <stdio.h>
#include <stdlib.h>

struct node { int data;
                      struct node * next; };
                      
                      int* mergeSort(int* buf1, int* buf2, long int size1, long int size2)
                      {
                        int *buf = (int *)malloc((size1+size2)*sizeof(int));
                    	long int i=0, j=0, k=0;
                    	    while(i!=size1 && j!=size2)
                    		{
                    			if(buf1[i]<buf2[j])
                    				{
                    					    buf[k++] = buf1[i++];
                    						    }
                    							    else
                    								    {
                    										buf[k++] = buf2[j++];
                    											}
                    											    }
                    												while(i!=size1)
                    												    {
                    													    buf[k++] = buf1[i++];
                    														}
                    														    while(j!=size2)
                    															{
                    																buf[k++] = buf2[j++];
                    																    }
                    																	return buf;
                    																	}
                    																	
                    																	void del(struct node *el)
                    																	{
                    																	    if(el->next!=NULL)
                    																		{
                    																			del(el->next);
                    																			    }
                    																				free(el);
                    																				}
                    																					  
                    																					  int main(argc, argv)
                    																					  int argc;
                    																					  char *argv[];
                    																					  {
                    																					      int value;
                    																					          if(argc<3)
                    																					              {
                    																					                      fprintf (stderr, "Недостаточно аргументов %s\n");
                    																					                              return 1;
                    																					                                  }
                    																					                                    FILE *files[argc-1];
                    																					                                        FILE *stream;
                    																					                                            int i;
                    																					                                        	if ((stream=fopen(argv[argc-1], "w"))==NULL)
                    																					                                        	    {
                    																					                                        	            fprintf (stderr, "%s не может открыть файл %s\n",
                    																					                                        	                    argv[0], argv[argc-1]);
                    																					                                        	                            return 1;
                    																					                                        	                                }
                    																					                                        	                                    files[0] = stream;
                    																					                                        	                                        for(i=1; i<argc-1; i++)
                    																					                                        	                                            {
                    																					                                        	                                                    if ((stream=fopen(argv[i], "r"))==NULL)
                    																					                                        	                                                            {
                    																					                                        	                                                                        fprintf (stderr, "%s не может открыть файл %s\n",
                    																					                                        	                                                                                    argv[0], argv[i]);
                    																					                                        	                                                                                		fcloseall();
                    																					                                        	                                                                                		            return 1;
                    																					                                        	                                                                                		                    }
                    																					                                        	                                                                                		                	    files[i] = stream;
                    																					                                        	                                                                                		                	        }
                    																					                                        	                                                                                		                	            struct node first;
                    																					                                        	                                                                                		                	        	first.data = 11111;
                    																					                                        	                                                                                		                	        	    first.next = NULL;
                    																					                                        	                                                                                		                	        		struct node *cur = &first;
                    																					                                        	                                                                                		                	        		    long int count = 0;
                    																					                                        	                                                                                		                	        			for(i=1; i<argc-1; i++)
                    																					                                        	                                                                                		                	        			    {
                    																					                                        	                                                                                		                	        			            stream = files[i];
                    																					                                        	                                                                                		                	        			        	    int err = err = fscanf(stream,"%d", &value);
                    																					                                        	                                                                                		                	        			        	            while(err!=0 && err!=EOF)
                    																					                                        	                                                                                		                	        			        	                    {
                    																					                                        	                                                                                		                	        			        	                		struct node *tmp = malloc(sizeof(struct node));
                    																					                                        	                                                                                		                	        			        	                			    count++;
                    																					                                        	                                                                                		                	        			        	                					if(tmp==NULL)
                    																					                                        	                                                                                		                	        			        	                						    {
                    																					                                        	                                                                                		                	        			        	                								    fprintf (stderr, "Хозяина, памяти мала\n");
                    																					                                        	                                                                                		                	        			        	                										    fcloseall();
                    																					                                        	                                                                                		                	        			        	                												    return 1;
                    																					                                        	                                                                                		                	        			        	                														}
                    																					                                        	                                                                                		                	        			        	                															    tmp->data = value;
                    																					                                        	                                                                                		                	        			        	                																	tmp->next = NULL;
                    																					                                        	                                                                                		                	        			        	                																		    cur->next = tmp;
                    																					                                        	                                                                                		                	        			        	                																				cur = cur->next;
                    																					                                        	                                                                                		                	        			        	                																					    err = fscanf(stream,"%d", &value);
                    																					                                        	                                                                                		                	        			        	                																					            }
                    																					                                        	                                                                                		                	        			        	                																					        	    if(err==0)
                    																					                                        	                                                                                		                	        			        	                																					        		    {
                    																					                                        	                                                                                		                	        			        	                																					        				fprintf (stderr, "Недопустимые символы в файле %s\n",
                    																					                                        	                                                                                		                	        			        	                																					        				            argv[i]);
                    																					                                        	                                                                                		                	        			        	                																					        				        		return 1;
                    																					                                        	                                                                                		                	        			        	                																					        				        			}
                    																					                                        	                                                                                		                	        			        	                																					        				        			    }
                    																					                                        	                                                                                		                	        			        	                																					        				        				int **buf = malloc(count*sizeof(int *));
                    																					                                        	                                                                                		                	        			        	                																					        				        				    int *size = malloc(count*sizeof(int));
                    																					                                        	                                                                                		                	        			        	                																					        				        					if(buf==NULL || size == NULL)
                    																					                                        	                                                                                		                	        			        	                																					        				        					    {
                    																					                                        	                                                                                		                	        			        	                																					        				        						    fprintf (stderr, "Хозяина, памяти мала\n");
                    																					                                        	                                                                                		                	        			        	                																					        				        								    fcloseall();
                    																					                                        	                                                                                		                	        			        	                																					        				        										    return 1;
                    																					                                        	                                                                                		                	        			        	                																					        				        											}
                    																					                                        	                                                                                		                	        			        	                																					        				        											    long int j = 0;
                    																					                                        	                                                                                		                	        			        	                																					        				        												cur = first.next;
                    																					                                        	                                                                                		                	        			        	                																					        				        												    while(cur!=NULL)
                    																					                                        	                                                                                		                	        			        	                																					        				        												        {
                    																					                                        	                                                                                		                	        			        	                																					        				        												    	    buf[j] = malloc(sizeof(int));
                    																					                                        	                                                                                		                	        			        	                																					        				        												    		    if(buf[j]==NULL)
                    																					                                        	                                                                                		                	        			        	                																					        				        												    			    {
                    																					                                        	                                                                                		                	        			        	                																					        				        												    					fprintf (stderr, "Хозяина, памяти мала\n");
                    																					                                        	                                                                                		                	        			        	                																					        				        												    							fcloseall();
                    																					                                        	                                                                                		                	        			        	                																					        				        												    									return 1;
                    																					                                        	                                                                                		                	        			        	                																					        				        												    										}
                    																					                                        	                                                                                		                	        			        	                																					        				        												    											buf[j][0] = cur->data;
                    																					                                        	                                                                                		                	        			        	                																					        				        												    												cur = cur->next;
                    																					                                        	                                                                                		                	        			        	                																					        				        												    													size[j] = 1;
                    																					                                        	                                                                                		                	        			        	                																					        				        												    														if(cur!=NULL)
                    																					                                        	                                                                                		                	        			        	                																					        				        												    															{
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																    j++;
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																	    }
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																		}
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																		    del(first.next);
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																			long int mSize = 1;
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																			    long int k = j;
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																				while(mSize!=j+1)
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																				    {
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																					    int **newBuf = malloc((((int)(k/2))+k%2)*sizeof(int *));
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																						    int *newSize = malloc((((int)(k/2))+k%2)*sizeof(int));
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																							    if(newBuf==NULL || newSize == NULL)
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																								    {
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																										fprintf (stderr, "Хозяина, памяти мала\n");
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																												fcloseall();
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																														return 1;
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																															}
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																int newK = ((int)((k+1)/2))+(k+1)%2-1;
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																	while(k>0)
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																		{
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																			    /*int l;
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																					printf("%s %d\n","k=",k);
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																						    for(l=0; l<size[k]; l++)
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																								{
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																										printf("%d\n", buf[k][l]);
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																											    }
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																													printf("%s","second");
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																														    for(l=0; l<size[k-1]; l++)
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																{
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																		printf("%d\n", buf[k-1][l]);
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																			    }*/
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																					newBuf[((int)((k+1)/2))+(k+1)%2-1] = mergeSort(buf[k], buf[k-1], size[k], size[k-1]);
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																						    if(newBuf[((int)((k+1)/2))+(k+1)%2-1]==NULL)
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																								{
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																										fprintf (stderr, "Хозяина, памяти мала\n");
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																												fcloseall();
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																														return 1;
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																															    }
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																	/*printf("%s","new");
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																		    for(l=0; l<size[k]+size[k-1]; l++)
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																				{
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																						printf("%d\n", newBuf[((int)((k+1)/2))+(k+1)%2-1][l]);
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																							    }*/
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																									free(buf[k]);
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																										    free(buf[k-1]);
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																												newSize[((int)((k+1)/2))+(k+1)%2-1] = size[k]+size[k-1];
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																													    k-=2;
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																														    }
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																															    if(k==0)
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																    {
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																		//printf("i this\n");
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																			    newBuf[0] = (int *)malloc(size[0]*sizeof(int));
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																					if(newBuf[0]==NULL)
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																						    {
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																								    fprintf (stderr, "Хозяина, памяти мала\n");
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																										    fcloseall();
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																												    return 1;
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																														}
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																															    int l;
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																	for(l=0;l<size[0]; l++)
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																		    {
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																				    //printf("this i\n");
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																						    newBuf[0][l]=buf[0][l];
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																								}
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																									    free(buf[0]);
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																											newSize[0] = size[0];
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																												}
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																													k = newK;
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																														free(buf);
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																															buf = newBuf;
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																/*printf("ololos\n");
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																	printf("ololos\n");
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																		printf("ololos\n");
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																			printf("ololos\n");
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																				printf("ololos\n");
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																					free(size);
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																						printf("ololos\n");
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																							printf("ololos\n");
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																								printf("ololos\n");*/ //- very fynny
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																									size = newSize;
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																										mSize = size[k];
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																											//printf("%s %d\n","new size ",mSize);
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																											    }
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																											        stream = files[0];
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																											    	for(i=0; i<=j; i++)
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																											    	    {
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																											    		    fprintf(stream,"%d\n", buf[0][i]);
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																											    			}
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																											    			    free(buf[0]);
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																											    				free(buf);
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																											    				    fcloseall();
                    																					                                        	                                                                                		                	        			        	                																					        				        												    																																																																																																																											    				        return 0;
}
